//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by English.rc
//
#define MSG_ERROR_IN_MESSAGE_QUEUE      1
#define MSG_ERROR_LIMIT_REACHED         2
#define MSG_ERROR_NOT_ENOUGH_MEMORY_FOR_EDIT 3
#define MSG_ERROR_NOT_ENOUGH_MEMORY     4
#define MSG_ERROR_BINARY                5
#define MSG_ERROR_IO                    6
#define MSG_ERROR_SYNTAX                8
#define MSG_ERROR_PRINT                 9
#define MSG_ERROR_RUN                   10
#define MSG_ERROR_LOAD_DLL              12
#define MSG_ERROR_UNLOAD_DLL            13
#define MSG_AUTOLOAD_IS_NOT_SUPPORTED   51
#define MSG_FUNCTION_NOT_FOUND          52
#define MSG_UPDATE_PROGRAM              53
#define MSG_PROGRAM_IS_NOT_SUPPORTED    54
#define MSG_UPDATE_PLUGIN               55
#define MSG_PLUGIN_IS_NOT_SUPPORTED     56
#define MSG_UPDATE_LANGMODULE           57
#define MSG_HOTKEY_EXISTS               58
#define MSG_CANNOT_OPEN_FILE            59
#define MSG_WRONG_STRING                60
#define MSG_LONG_FILELIST               61
#define MSG_DOCUMENT_CHANGED            62
#define MSG_FILE_DOES_NOT_EXIST         63
#define MSG_RECENTFILES_DELETED         64
#define MSG_SEARCH_ENDED                65
#define MSG_REPLACE_COUNT               66
#define MSG_REPLACE_COUNT_ALLFILES      67
#define MSG_FILE_WILL_BE_REOPENED       68
#define MSG_FILE_CHANGED                69
#define MSG_CP_UNIMPLEMENTED            70
#define MSG_CP_MISMATCH                 71
#define MSG_RESTART_PROGRAM             72
#define MSG_SAVEIN_READONLY             73
#define STR_DOCNAME                     101
#define STR_MODIFIED                    102
#define STR_AUTODETECT                  103
#define STR_RECENT_FILES_EMPTY          104
#define STR_RECENT_FILES_DELETE_DEAD    105
#define STR_OPTIONS                     106
#define STR_LANGUAGE_NONE               107
#define STR_FILE_FILTER                 108
#define STR_EXECUTABLE_FILTER           109
#define STR_DEFAULT_SAVE_EXT            110
#define STR_NONE                        111
#define STR_PLUGIN                      112
#define STR_FUNCTION                    113
#define STR_HOTKEY                      114
#define STR_STATUS                      115
#define STR_RUNNING                     116
#define STR_FONT                        117
#define STR_HEADLINE                    118
#define STR_TOP                         119
#define STR_BOTTOM                      120
#define STR_ELEMENT                     121
#define STR_STANDARDTHEME               122
#define STR_TEXT                        123
#define STR_BACKGROUND                  124
#define STR_SAMPLE                      125
#define STR_BASIC                       126
#define STR_SELECTION                   127
#define STR_ACTIVELINE                  128
#define STR_ACTIVECOLUMN                129
#define STR_COLUMNMARKER                130
#define STR_CARET                       131
#define STR_URL                         132
#define STR_PAGEFIT                     133
#define STR_PAGEWIDTH                   134
#define STR_AUTODETECT_RUSSIAN          501
#define STR_AUTODETECT_ENGLISH          502
#define STR_AUTODETECT_TURKISH          503
#define STR_AUTODETECT_CHINESE          504
#define STR_AUTODETECT_JAPANESE         505
#define STR_AUTODETECT_KOREAN           506
#define RESERVED                        1000
#define IDI_ICON_MAIN                   1001
#define IDI_ICON_EMPTY                  1002
#define IDC_CURSOR_DRAGMOVE             1101
#define IDC_CURSOR_HANDOPEN             1102
#define IDC_CURSOR_HANDCLOSE            1103
#define IDB_BITMAP_DOWNARROW            1201
#define IDB_BITMAP_CLOSE                1202
#define IDA_ACCEL_GLOBAL                1301
#define IDA_ACCEL_MAIN                  1302
#define IDD_OFN                         2001
#define IDD_MDILIST                     2002
#define IDD_PRINTPREVIEW                2003
#define IDD_FIND                        2004
#define IDD_REPLACE                     2005
#define IDD_GOTOLINE                    2006
#define IDD_RECODE                      2007
#define IDD_COLORS                      2008
#define IDD_PLUGINS                     2009
#define IDD_OPTIONS_GENERAL             2010
#define IDD_OPTIONS_GENERAL_FILTER      2011
#define IDD_OPTIONS_REGISTRY            2012
#define IDD_OPTIONS_EDITOR              2013
#define IDD_OPTIONS_ADVANCED            2014
#define IDD_OPTIONS_ADVANCED1_3X        2021
#define IDD_OPTIONS_ADVANCED2_3X        2022
#define IDD_ABOUT                       2051
#define IDC_OFN_AUTODETECT              2501
#define IDC_OFN_CODEPAGE                2502
#define IDC_OFN_PREVIEW                 2503
#define IDC_OFN_CODEPAGE_LABEL          2504
#define IDC_MDILIST_LIST                2551
#define IDC_MDILIST_STATS               2552
#define IDC_MDILIST_SEARCH              2553
#define IDC_MDILIST_ARRANGE_GROUP       2554
#define IDC_MDILIST_HORZ                2555
#define IDC_MDILIST_VERT                2556
#define IDC_MDILIST_TABS_GROUP          2557
#define IDC_MDILIST_UP                  2558
#define IDC_MDILIST_DOWN                2559
#define IDC_MDILIST_SORT                2560
#define IDC_MDILIST_ONLYMODIFIED        2561
#define IDC_MDILIST_FILES_GROUP         2562
#define IDC_MDILIST_SAVE                2563
#define IDC_MDILIST_CLOSE               2564
#define IDC_PREVIEW_BOX                 3001
#define IDC_PREVIEW_PRINT               3002
#define IDC_PREVIEW_PAGESETUP           3003
#define IDC_PREVIEW_FIRSTPAGE           3004
#define IDC_PREVIEW_LASTPAGE            3005
#define IDC_PREVIEW_PREVPAGE            3006
#define IDC_PREVIEW_NEXTPAGE            3007
#define IDC_PREVIEW_PAGECOUNT           3008
#define IDC_PREVIEW_ZOOM                3009
#define IDC_PREVIEW_ZOOMIN              3010
#define IDC_PREVIEW_ZOOMOUT             3011
#define IDC_PREVIEW_SELECTION           3012
#define IDC_SETREADONLY                 3051
#define IDC_SEARCH_FIND                 3052
#define IDC_SEARCH_REPLACE              3053
#define IDC_SEARCH_MATCHCASE            3054
#define IDC_SEARCH_WHOLEWORD            3055
#define IDC_SEARCH_ESCAPESEQ            3056
#define IDC_SEARCH_BACKWARD             3057
#define IDC_SEARCH_FORWARD              3058
#define IDC_SEARCH_BEGINNING            3059
#define IDC_SEARCH_INSEL                3060
#define IDC_SEARCH_ALLFILES_GROUP       3061
#define IDC_SEARCH_ALLFILES             3062
#define IDC_SEARCH_FIND_BUTTON          3063
#define IDC_SEARCH_REPLACE_BUTTON       3064
#define IDC_SEARCH_ALL_BUTTON           3065
#define IDC_GOTOLINE_NUMBER             3101
#define IDC_GOTOLINE_LINE               3102
#define IDC_GOTOLINE_OFFSET             3103
#define IDC_RECODE_CODEPAGE_FROM        3151
#define IDC_RECODE_CODEPAGE_TO          3152
#define IDC_COLORS_LIST                 3201
#define IDC_COLORS_THEME_NAME           3202
#define IDC_COLORS_THEME_SAVE           3203
#define IDC_COLORS_THEME_DELETE         3204
#define IDC_PLUGINS_LIST                3251
#define IDC_PLUGINS_HOTKEY              3252
#define IDC_PLUGINS_ASSIGN              3253
#define IDC_PLUGINS_CALL                3254
#define IDC_PLUGINS_HOTKEY_LABEL        3255
#define IDC_PLUGINS_LIST_INFO           3256
#define IDC_OPTIONS_EXECCOM             3501
#define IDC_OPTIONS_EXECCOM_BROWSE      3502
#define IDC_OPTIONS_EXECDIR             3503
#define IDC_OPTIONS_EXECDIR_BROWSE      3504
#define IDC_OPTIONS_CODEPAGE_RECOGNITION 3505
#define IDC_OPTIONS_CODEPAGE_RECOGNITION_BUFFER 3506
#define IDC_OPTIONS_DEFAULT_CODEPAGE    3507
#define IDC_OPTIONS_CODEPAGE_FILTER     3508
#define IDC_OPTIONS_CODEPAGES_FILTER_CUSTOM 3509
#define IDC_OPTIONS_CODEPAGES_FILTER_SYSTEM 3510
#define IDC_OPTIONS_CODEPAGES_FILTER_UP 3511
#define IDC_OPTIONS_CODEPAGES_FILTER_DOWN 3512
#define IDC_OPTIONS_CODEPAGES_FILTER_ADD 3513
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETE 3514
#define IDC_OPTIONS_CODEPAGES_FILTER_ADDALL 3515
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETEALL 3516
#define IDC_OPTIONS_NEWLINE_WIN         3517
#define IDC_OPTIONS_NEWLINE_UNIX        3518
#define IDC_OPTIONS_NEWLINE_MAC         3519
#define IDC_OPTIONS_SAVESETTINGS_REGISTRY 3551
#define IDC_OPTIONS_SAVESETTINGS_INI    3552
#define IDC_OPTIONS_SAVEPOSITIONS       3553
#define IDC_OPTIONS_SAVECODEPAGES       3554
#define IDC_OPTIONS_RECENTFILES_AMOUNT  3555
#define IDC_OPTIONS_RECENTFILES_AMOUNT_SPIN 3556
#define IDC_OPTIONS_RECENTFILES_CLEAR   3557
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT 3558
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT_SPIN 3559
#define IDC_OPTIONS_SEARCHSTRINGS_CLEAR 3560
#define IDC_OPTIONS_FILETYPES_OPEN      3561
#define IDC_OPTIONS_ASSOCIATE_OPEN      3562
#define IDC_OPTIONS_FILETYPES_EDIT      3563
#define IDC_OPTIONS_ASSOCIATE_EDIT      3564
#define IDC_OPTIONS_FILETYPES_PRINT     3565
#define IDC_OPTIONS_ASSOCIATE_PRINT     3566
#define IDC_OPTIONS_EDITMARGIN_LEFT     3601
#define IDC_OPTIONS_EDITMARGIN_LEFT_SPIN 3602
#define IDC_OPTIONS_EDITMARGIN_SELECTION 3603
#define IDC_OPTIONS_EDITMARGIN_RIGHT    3604
#define IDC_OPTIONS_EDITMARGIN_RIGHT_SPIN 3605
#define IDC_OPTIONS_TABSIZE             3606
#define IDC_OPTIONS_TABSIZE_SPIN        3607
#define IDC_OPTIONS_TABSIZE_SPACES      3608
#define IDC_OPTIONS_UNDO_LIMIT          3609
#define IDC_OPTIONS_UNDO_LIMIT_SPIN     3610
#define IDC_OPTIONS_UNDO_DETAILED       3611
#define IDC_OPTIONS_WRAP_BY_WORDS       3612
#define IDC_OPTIONS_WRAP_BY_SYMBOLS     3613
#define IDC_OPTIONS_WRAP_LIMIT          3614
#define IDC_OPTIONS_WRAP_LIMIT_SPIN     3615
#define IDC_OPTIONS_CARETOUTEDGE        3616
#define IDC_OPTIONS_CARETVERTLINE       3617
#define IDC_OPTIONS_CARETWIDTH          3618
#define IDC_OPTIONS_CARETWIDTH_SPIN     3619
#define IDC_OPTIONS_MARKER              3620
#define IDC_OPTIONS_MARKER_SPIN         3621
#define IDC_OPTIONS_LINEGAP             3622
#define IDC_OPTIONS_LINEGAP_SPIN        3623
#define IDC_OPTIONS_URL_SHOW            3651
#define IDC_OPTIONS_URL_SINGLECLICK     3652
#define IDC_OPTIONS_URL_DOUBLECLICK     3653
#define IDC_OPTIONS_URL_PREFIXES_ENABLE 3654
#define IDC_OPTIONS_URL_PREFIXES        3655
#define IDC_OPTIONS_URL_DELIMITERS_ENABLE 3656
#define IDC_OPTIONS_URL_LEFTDELIMITERS  3657
#define IDC_OPTIONS_URL_RIGHTDELIMITERS 3658
#define IDC_OPTIONS_WORD_DELIMITERS_ENABLE 3659
#define IDC_OPTIONS_WORD_DELIMITERS     3660
#define IDC_OPTIONS_WORD_DELIMITERS_RESET 3661
#define IDC_OPTIONS_WRAP_DELIMITERS_ENABLE 3662
#define IDC_OPTIONS_WRAP_DELIMITERS     3663
#define IDC_OPTIONS_WRAP_DELIMITERS_RESET 3664
#define IDC_OPTIONS_REPLACEALL_CLOSE    3665
#define IDC_OPTIONS_SAVEIN_READONLY_MSG 3666
#define IDC_ABOUT_ICON                  3901
#define IDC_ABOUT_VERSION               3902
#define IDC_ABOUT_HOMEPAGE              3903
#define IDC_ABOUT_EMAIL_KUZNETSOV       3904
#define IDC_ABOUT_EMAIL_SHENGALTS       3905
#define IDM_MENU_MAIN                   4001
#define IDM_MENU_POPUP                  4002
#define IDM_FILE_NEW                    4101
#define IDM_FILE_CREATENEW              4102
#define IDM_FILE_OPEN                   4103
#define IDM_FILE_REOPEN                 4104
#define IDM_FILE_SAVE                   4105
#define IDM_FILE_SAVEAS                 4106
#define IDM_FILE_PAGESETUP              4107
#define IDM_FILE_PRINT                  4108
#define IDM_FILE_EXIT                   4109
#define IDM_FILE_SAVEALL                4110
#define IDM_FILE_CLOSEALL               4111
#define IDM_FILE_CLOSEALL_BUTACTIVE     4112
#define IDM_FILE_SILENTPRINT            4113
#define IDM_FILE_PRINTPREVIEW           4114
#define IDM_EDIT_UNDO                   4151
#define IDM_EDIT_REDO                   4152
#define IDM_EDIT_CUT                    4153
#define IDM_EDIT_COPY                   4154
#define IDM_EDIT_PASTE                  4155
#define IDM_EDIT_CLEAR                  4156
#define IDM_EDIT_SELECTALL              4157
#define IDM_EDIT_FIND                   4158
#define IDM_EDIT_FINDNEXTDOWN           4159
#define IDM_EDIT_FINDNEXTUP             4160
#define IDM_EDIT_REPLACE                4161
#define IDM_EDIT_GOTOLINE               4162
#define IDM_EDIT_INSERTCHAR             4163
#define IDM_EDIT_INSERT_TAB             4164
#define IDM_EDIT_INSERT_TAB_MENU        4165
#define IDM_EDIT_DELETE_TAB             4166
#define IDM_EDIT_DELETE_TAB_MENU        4167
#define IDM_EDIT_INSERT_SPACE           4168
#define IDM_EDIT_INSERT_SPACE_MENU      4169
#define IDM_EDIT_DELETE_SPACE           4170
#define IDM_EDIT_DELETE_SPACE_MENU      4171
#define IDM_EDIT_DELETE_FIRST_CHAR      4172
#define IDM_EDIT_DELETE_FIRST_CHAR_MENU 4173
#define IDM_EDIT_DELETE_TRAILING_WHITESPACES 4174
#define IDM_EDIT_UPPERCASE              4175
#define IDM_EDIT_LOWERCASE              4176
#define IDM_EDIT_SENTENCECASE           4177
#define IDM_EDIT_TITLECASE              4178
#define IDM_EDIT_INVERTCASE             4179
#define IDM_EDIT_LOOPCASE               4180
#define IDM_EDIT_RECODE                 4182
#define IDM_EDIT_INSERTDATE             4183
#define IDM_EDIT_NEWLINE_WIN            4184
#define IDM_EDIT_NEWLINE_UNIX           4185
#define IDM_EDIT_NEWLINE_MAC            4186
#define IDM_VIEW_FONT                   4201
#define IDM_VIEW_COLORS                 4202
#define IDM_VIEW_TEXT_COLOR_3X          4202
#define IDM_VIEW_BG_COLOR_3X            4203
#define IDM_VIEW_INCREASE_FONT          4204
#define IDM_VIEW_DECREASE_FONT          4205
#define IDM_VIEW_ALIGN_LEFT_3X          4206
#define IDM_VIEW_ALIGN_CENTER_3X        4207
#define IDM_VIEW_ALIGN_RIGHT_3X         4208
#define IDM_VIEW_WORDWRAP               4209
#define IDM_VIEW_ONTOP                  4210
#define IDM_VIEW_SHOW_STATUSBAR         4211
#define IDM_VIEW_SPLIT_WINDOW_ALL       4212
#define IDM_VIEW_SPLIT_WINDOW_WE        4213
#define IDM_VIEW_SPLIT_WINDOW_NS        4214
#define IDM_OPTIONS_EXEC                4251
#define IDM_OPTIONS_SAVETIME            4252
#define IDM_OPTIONS_WATCHFILE           4253
#define IDM_OPTIONS_KEEPSPACE           4254
#define IDM_OPTIONS_SINGLEOPEN_FILE     4255
#define IDM_OPTIONS_SINGLEOPEN_PROGRAM  4256
#define IDM_OPTIONS_SDI                 4257
#define IDM_OPTIONS_MDI                 4258
#define IDM_OPTIONS_PLUGINS             4259
#define IDM_OPTIONS                     4260
#define IDM_OPTIONS_READONLY            4261
#define IDM_WINDOW_TABVIEW_TOP          4301
#define IDM_WINDOW_TABVIEW_BOTTOM       4302
#define IDM_WINDOW_TABVIEW_NONE         4303
#define IDM_WINDOW_TABTYPE_STANDARD     4304
#define IDM_WINDOW_TABTYPE_BUTTONS      4305
#define IDM_WINDOW_TABTYPE_FLATBUTTONS  4306
#define IDM_WINDOW_TILEHORIZONTAL       4307
#define IDM_WINDOW_TILEVERTICAL         4308
#define IDM_WINDOW_CASCADE              4309
#define IDM_WINDOW_TABSWITCH_NEXTPREV   4310
#define IDM_WINDOW_TABSWITCH_RIGHTLEFT  4311
#define IDM_ABOUT                       4351
#define IDM_NONMENU_CHANGESIZE          4401
#define IDM_NONMENU_DELLINE             4402
#define IDM_NONMENU_PASTEANSI           4403
#define IDM_NONMENU_MDINEXT             4404
#define IDM_NONMENU_MDIPREV             4405
#define IDM_NONMENU_MDICLOSE            4406
#define IDM_NONMENU_REOPEN_MSG          4407
#define IDM_NONMENU_REDETECT            4408
#define IDM_NONMENU_REOPENAS_ANSI       4409
#define IDM_NONMENU_REOPENAS_OEM        4410
#define IDM_NONMENU_REOPENAS_UTF16LE    4411
#define IDM_NONMENU_REOPENAS_UTF16BE    4412
#define IDM_NONMENU_REOPENAS_UTF8       4413
#define IDM_NONMENU_REOPENAS_KOIR       4414
#define IDM_NONMENU_SAVEAS_ANSI         4415
#define IDM_NONMENU_SAVEAS_OEM          4416
#define IDM_NONMENU_SAVEAS_UTF16LE      4417
#define IDM_NONMENU_SAVEAS_UTF16BE      4418
#define IDM_NONMENU_SAVEAS_UTF8         4419
#define IDM_NONMENU_SAVEAS_KOIR         4420
#define IDM_NONMENU_INSERTMODE          4421
#define IDM_NONMENU_FILECLOSE           4422
#define IDM_NONMENU_DLGNEXT             4423
#define IDM_NONMENU_DLGPREV             4424
#define IDM_NONMENU_AUTOINDENT          4425
#define IDM_NONMENU_SAVEAS_UTF8_NOBOM   4426
#define IDM_NONMENU_CLONENEXT           4427
#define IDM_NONMENU_CLONEPREV           4428
#define IDM_NONMENU_COLUMNPASTE         4429
#define IDM_NONMENU_PASTEAFTER          4430
#define IDM_NONMENU_CANTOPEN_MSG        4431
#define IDM_POPUP_CODEPAGEMENU          4501
#define IDM_POPUP_HEADLINE_SYMBOL       4502
#define IDM_POPUP_HEADLINE_PAGE_NUMBER  4503
#define IDM_POPUP_HEADLINE_FILE_NAME    4504
#define IDM_POPUP_HEADLINE_ALIGN_CENTER 4505
#define IDM_POPUP_HEADLINE_ALIGN_LEFT   4506
#define IDM_POPUP_HEADLINE_ALIGN_RIGHT  4507
#define IDM_RECENT_FILES                5001
#define IDM_LANGUAGE                    6001
#define IDM_POPUP_OPENAS                7001
#define IDM_POPUP_SAVEAS                8001
#define IDM_SELECTWINDOW                10019
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11001
#define _APS_NEXT_COMMAND_VALUE         12001
#define _APS_NEXT_CONTROL_VALUE         13001
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
