//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by English.rc
//
#define MSG_ERROR_IN_MESSAGE_QUEUE      1
#define MSG_ERROR_LIMIT_REACHED         2
#define MSG_ERROR_NOT_ENOUGH_MEMORY_FOR_RICHEDIT 3
#define MSG_ERROR_NOT_ENOUGH_MEMORY     4
#define MSG_ERROR_BINARY                5
#define MSG_ERROR_IO                    6
#define MSG_ERROR_CANNOT_OPEN_FILE      7
#define MSG_ERROR_SYNTAX                8
#define MSG_ERROR_PRINT                 9
#define MSG_ERROR_RUN                   10
#define MSG_ERROR_FUNCTION_NOT_FOUND    11
#define MSG_ERROR_LOAD_DLL              12
#define MSG_ERROR_UNLOAD_DLL            13
#define MSG_WRONG_STRING                14
#define MSG_LONG_FILELIST               15
#define MSG_DOCUMENT_CHANGED            16
#define MSG_FILE_DOES_NOT_EXIST         17
#define MSG_RECENTFILES_DELETED         18
#define MSG_SEARCH_ENDED                19
#define MSG_REPLACE_COUNT               20
#define MSG_REPLACE_COUNT_ALLFILES      21
#define MSG_FILE_WILL_BE_REOPENED       22
#define MSG_FILE_CHANGED                23
#define MSG_CP_UNIMPLEMENTED            24
#define MSG_RESTART_PROGRAM             25
#define MSG_SAVEIN_READONLY             26
#define MSG_HOTKEY_EXISTS               27
#define MSG_AUTOLOAD_DOES_NOT_SUPPORTED 28
#define STR_DOCNAME                     51
#define STR_MODIFIED                    52
#define STR_AUTODETECT                  53
#define STR_RECENT_FILES_EMPTY          54
#define STR_RECENT_FILES_DELETE_DEAD    55
#define STR_OPTIONS                     56
#define STR_LANGUAGE_NONE               57
#define STR_FILE_FILTER                 58
#define STR_NONE                        59
#define STR_AUTODETECT_RUSSIAN          60
#define STR_PLUGIN_FUNCTION             61
#define STR_HOTKEY                      62
#define STR_STATUS                      63
#define STR_RUNNING                     64
#define STR_EXECUTABLE_FILTER           65
#define STR_FONT                        66
#define STR_HEADLINE                    67
#define STR_TOP                         68
#define STR_BOTTOM                      69
#define RESERVED                        1000
#define IDI_ICON_MAIN                   1001
#define IDI_ICON_EMPTY                  1002
#define IDC_CURSOR_DRAGMOVE             1101
#define IDB_BITMAP_DOWNARROW            1201
#define IDA_ACCEL_GLOBAL                1301
#define IDA_ACCEL_MAIN                  1302
#define IDD_OFN                         2001
#define IDD_FIND                        2002
#define IDD_REPLACE                     2003
#define IDD_GOTOLINE                    2004
#define IDD_RECODE                      2005
#define IDD_PLUGINS                     2006
#define IDD_OPTIONS_GENERAL             2007
#define IDD_OPTIONS_ADVANCED1           2008
#define IDD_ABOUT                       2009
#define IDD_OPTIONS_GENERAL_FILTER      2010
#define IDD_OPTIONS_ADVANCED2           2011
#define IDC_OFN_AUTODETECT              3001
#define IDC_OFN_CODEPAGE                3002
#define IDC_OFN_PREVIEW                 3003
#define IDC_OFN_CODEPAGE_LABEL          3004
#define IDC_SEARCH_ALL_BUTTON           3051
#define IDC_SEARCH_BACKWARD             3052
#define IDC_SEARCH_BEGINNING            3053
#define IDC_SEARCH_ESCAPESEQ            3054
#define IDC_SEARCH_FIND                 3055
#define IDC_SEARCH_FIND_BUTTON          3056
#define IDC_SEARCH_FORWARD              3057
#define IDC_SEARCH_INSEL                3058
#define IDC_SEARCH_MATCHCASE            3059
#define IDC_SEARCH_REPLACE              3060
#define IDC_SEARCH_REPLACE_BUTTON       3061
#define IDC_SEARCH_ALLFILES             3063
#define IDC_SEARCH_ALLFILES_GROUP       3064
#define IDC_SETREADONLY                 3065
#define IDC_GOTOLINE                    3101
#define IDC_RECODE_CODEPAGE_FROM        3151
#define IDC_RECODE_CODEPAGE_TO          3152
#define IDC_OPTIONS_RECENTFILES_AMOUNT  3501
#define IDC_OPTIONS_RECENTFILES_AMOUNT_SPIN 3502
#define IDC_OPTIONS_RECENTFILES_CLEAR   3503
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT 3504
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT_SPIN 3505
#define IDC_OPTIONS_SEARCHSTRINGS_CLEAR 3506
#define IDC_OPTIONS_EXECCOM             3507
#define IDC_OPTIONS_EXECCOM_BROWSE      3508
#define IDC_OPTIONS_EXECDIR             3509
#define IDC_OPTIONS_EXECDIR_BROWSE      3510
#define IDC_OPTIONS_DEFAULT_CODEPAGE    3511
#define IDC_OPTIONS_CODEPAGE_FILTER     3512
#define IDC_OPTIONS_CODEPAGES_FILTER_CUSTOM 3513
#define IDC_OPTIONS_CODEPAGES_FILTER_SYSTEM 3514
#define IDC_OPTIONS_CODEPAGES_FILTER_UP 3515
#define IDC_OPTIONS_CODEPAGES_FILTER_DOWN 3516
#define IDC_OPTIONS_CODEPAGES_FILTER_ADD 3517
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETE 3518
#define IDC_OPTIONS_CODEPAGES_FILTER_ADDALL 3519
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETEALL 3520
#define IDC_OPTIONS_CODEPAGE_RECOGNITION 3521
#define IDC_OPTIONS_CODEPAGE_RECOGNITION_BUFFER 3522
#define IDC_OPTIONS_FILETYPES_OPEN      3523
#define IDC_OPTIONS_ASSOCIATE_OPEN      3524
#define IDC_OPTIONS_FILETYPES_EDIT      3525
#define IDC_OPTIONS_ASSOCIATE_EDIT      3526
#define IDC_OPTIONS_FILETYPES_PRINT     3527
#define IDC_OPTIONS_ASSOCIATE_PRINT     3528
#define IDC_OPTIONS_TABSIZE             3529
#define IDC_OPTIONS_TABSIZE_SPIN        3530
#define IDC_OPTIONS_TABSIZE_SPACES      3531
#define IDC_OPTIONS_UNDO_LIMIT          3532
#define IDC_OPTIONS_UNDO_LIMIT_SPIN     3533
#define IDC_OPTIONS_UNDO_DETAILED       3534
#define IDC_OPTIONS_SAVESETTINGS_REGISTRY 3535
#define IDC_OPTIONS_SAVESETTINGS_INI    3536
#define IDC_OPTIONS_EDITMARGIN_LEFT     3537
#define IDC_OPTIONS_EDITMARGIN_LEFT_SPIN 3538
#define IDC_OPTIONS_EDITMARGIN_RIGHT    3539
#define IDC_OPTIONS_EDITMARGIN_RIGHT_SPIN 3540
#define IDC_OPTIONS_WORD_DELIMITERS_ENABLE 3541
#define IDC_OPTIONS_WORD_DELIMITERS     3542
#define IDC_OPTIONS_WORD_DELIMITERS_RESET    3543
#define IDC_OPTIONS_SAVECODEPAGES       3544
#define IDC_OPTIONS_SAVEPOSITIONS       3545
#define IDC_OPTIONS_URL_SHOW            3546
#define IDC_OPTIONS_URL_SINGLECLICK     3547
#define IDC_OPTIONS_URL_DOUBLECLICK     3548
#define IDC_OPTIONS_URL_PREFIXES_ENABLE 3549
#define IDC_OPTIONS_URL_PREFIXES        3550
#define IDC_OPTIONS_URL_DELIMITERS_ENABLE 3551
#define IDC_OPTIONS_URL_DELIMITERS      3552
#define IDC_OPTIONS_REPLACEALL_CLOSE    3553
#define IDC_OPTIONS_SAVEIN_READONLY_MSG 3554
#define IDC_PLUGINS_LIST                3301
#define IDC_PLUGINS_HOTKEY              3302
#define IDC_PLUGINS_ASSIGN              3303
#define IDC_PLUGINS_CALL                3304
#define IDC_PLUGINS_CLEAR_OLD           3305
#define IDC_ABOUT_ICON                  3351
#define IDC_ABOUT_VERSION               3352
#define IDC_ABOUT_HOMEPAGE              3353
#define IDC_ABOUT_EMAIL_KUZNETSOV       3354
#define IDC_ABOUT_EMAIL_SHENGALTS       3355
#define IDM_MENU_MAIN                   4001
#define IDM_MENU_POPUP                  4002
#define IDM_FILE_NEW                    4101
#define IDM_FILE_CREATENEW              4102
#define IDM_FILE_OPEN                   4103
#define IDM_FILE_REOPEN                 4104
#define IDM_FILE_SAVE                   4105
#define IDM_FILE_SAVEAS                 4106
#define IDM_FILE_PAGESETUP              4107
#define IDM_FILE_PRINT                  4108
#define IDM_FILE_EXIT                   4109
#define IDM_FILE_SAVEALL                4110
#define IDM_FILE_CLOSEALL               4111
#define IDM_FILE_CLOSEALL_BUTACTIVE     4112
#define IDM_EDIT_UNDO                   4151
#define IDM_EDIT_REDO                   4152
#define IDM_EDIT_CUT                    4153
#define IDM_EDIT_COPY                   4154
#define IDM_EDIT_PASTE                  4155
#define IDM_EDIT_CLEAR                  4156
#define IDM_EDIT_SELECTALL              4157
#define IDM_EDIT_FIND                   4158
#define IDM_EDIT_FINDNEXTDOWN           4159
#define IDM_EDIT_FINDNEXTUP             4160
#define IDM_EDIT_REPLACE                4161
#define IDM_EDIT_GOTOLINE               4162
#define IDM_EDIT_INSERTCHAR             4163
#define IDM_EDIT_INSERT_TAB             4164
#define IDM_EDIT_INSERT_TAB_MENU        4165
#define IDM_EDIT_DELETE_TAB             4166
#define IDM_EDIT_DELETE_TAB_MENU        4167
#define IDM_EDIT_INSERT_SPACE           4168
#define IDM_EDIT_INSERT_SPACE_MENU      4169
#define IDM_EDIT_DELETE_SPACE           4170
#define IDM_EDIT_DELETE_SPACE_MENU      4171
#define IDM_EDIT_DELETE_FIRST_CHAR      4172
#define IDM_EDIT_DELETE_FIRST_CHAR_MENU 4173
#define IDM_EDIT_DELETE_TRAILING_WHITESPACES 4174
#define IDM_EDIT_UPPERCASE              4175
#define IDM_EDIT_LOWERCASE              4176
#define IDM_EDIT_SENTENCECASE           4177
#define IDM_EDIT_TITLECASE              4178
#define IDM_EDIT_INVERTCASE             4179
#define IDM_EDIT_RECODE                 4182
#define IDM_EDIT_INSERTDATE             4183
#define IDM_EDIT_NEWLINE_WIN            4184
#define IDM_EDIT_NEWLINE_UNIX           4185
#define IDM_EDIT_NEWLINE_MAC            4186
#define IDM_VIEW_FONT                   4201
#define IDM_VIEW_TEXT_COLOR             4202
#define IDM_VIEW_BG_COLOR               4203
#define IDM_VIEW_INCREASE_FONT          4204
#define IDM_VIEW_DECREASE_FONT          4205
#define IDM_VIEW_ALIGN_LEFT             4206
#define IDM_VIEW_ALIGN_CENTER           4207
#define IDM_VIEW_ALIGN_RIGHT            4208
#define IDM_VIEW_WORDWRAP               4209
#define IDM_VIEW_ONTOP                  4210
#define IDM_VIEW_SHOW_STATUSBAR         4211
#define IDM_OPTIONS_EXEC                4251
#define IDM_OPTIONS_SAVETIME            4252
#define IDM_OPTIONS_WATCHFILE           4253
#define IDM_OPTIONS_KEEPSPACE           4254
#define IDM_OPTIONS_SINGLEOPEN_FILE     4255
#define IDM_OPTIONS_SINGLEOPEN_PROGRAM  4256
#define IDM_OPTIONS_SDI                 4257
#define IDM_OPTIONS_MDI                 4258
#define IDM_OPTIONS_PLUGINS             4259
#define IDM_OPTIONS                     4260
#define IDM_OPTIONS_READONLY            4261
#define IDM_WINDOW_TABVIEW_TOP          4301
#define IDM_WINDOW_TABVIEW_BOTTOM       4302
#define IDM_WINDOW_TABVIEW_NONE         4303
#define IDM_WINDOW_TABTYPE_STANDARD     4304
#define IDM_WINDOW_TABTYPE_BUTTONS      4305
#define IDM_WINDOW_TABTYPE_FLATBUTTONS  4306
#define IDM_WINDOW_TILEHORIZONTAL       4307
#define IDM_WINDOW_TILEVERTICAL         4308
#define IDM_WINDOW_CASCADE              4309
#define IDM_WINDOW_TABSWITCH_NEXTPREV   4310
#define IDM_WINDOW_TABSWITCH_RIGHTLEFT  4311
#define IDM_ABOUT                       4351
#define IDM_NONMENU_CHANGESIZE          4401
#define IDM_NONMENU_DELLINE             4402
#define IDM_NONMENU_PASTEANSI           4403
#define IDM_NONMENU_MDINEXT             4404
#define IDM_NONMENU_MDIPREV             4405
#define IDM_NONMENU_MDICLOSE            4406
#define IDM_NONMENU_REOPEN_MSG          4407
#define IDM_NONMENU_REDETECT            4408
#define IDM_NONMENU_REOPENAS_ANSI       4409
#define IDM_NONMENU_REOPENAS_OEM        4410
#define IDM_NONMENU_REOPENAS_UTF16LE    4411
#define IDM_NONMENU_REOPENAS_UTF16BE    4412
#define IDM_NONMENU_REOPENAS_UTF8       4413
#define IDM_NONMENU_REOPENAS_KOIR       4414
#define IDM_NONMENU_SAVEAS_ANSI         4415
#define IDM_NONMENU_SAVEAS_OEM          4416
#define IDM_NONMENU_SAVEAS_UTF16LE      4417
#define IDM_NONMENU_SAVEAS_UTF16BE      4418
#define IDM_NONMENU_SAVEAS_UTF8         4419
#define IDM_NONMENU_SAVEAS_KOIR         4420
#define IDM_NONMENU_INSERTMODE          4421
#define IDM_NONMENU_FILECLOSE           4422
#define IDM_NONMENU_DLGNEXT             4423
#define IDM_NONMENU_DLGPREV             4424
#define IDM_POPUP_CODEPAGEMENU          4501
#define IDM_POPUP_HEADLINE_SYMBOL       4502
#define IDM_POPUP_HEADLINE_PAGE_NUMBER  4503
#define IDM_POPUP_HEADLINE_FILE_NAME    4504
#define IDM_POPUP_HEADLINE_ALIGN_CENTER 4505
#define IDM_POPUP_HEADLINE_ALIGN_LEFT   4506
#define IDM_POPUP_HEADLINE_ALIGN_RIGHT  4507
#define IDM_RECENT_FILES                5001
#define IDM_LANGUAGE                    6001
#define IDM_POPUP_OPENAS                7001
#define IDM_POPUP_SAVEAS                8001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11001
#define _APS_NEXT_COMMAND_VALUE         12001
#define _APS_NEXT_CONTROL_VALUE         13001
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
