#ifndef __LANGPACK_H__
#define __LANGPACK_H__

/*
* The following constant applies to:
* APP_SHORT_TITLE
*/

#define STD_LANGPACK_STRING_LENGTH 256

extern TCHAR APP_SHORT_TITLE[];
extern TCHAR APP_FULL_TITLE[];

extern TCHAR STR_DUMMY_NAME[];

extern TCHAR STR_MODE_INSERT[];
extern TCHAR STR_MODE_OVERLAP[];
extern TCHAR STR_MODIFIED[];

extern TCHAR STR_CP_WINDOWS[];
extern TCHAR STR_CP_DOS[];
extern TCHAR STR_CP_KOI[];
extern TCHAR STR_CP_UNICODE_UCS2_LE[];
extern TCHAR STR_CP_UNICODE_UCS2_BE[];
extern TCHAR STR_CP_UNICODE_UTF8[];

extern TCHAR STR_FILE_FILTER[];

extern TCHAR STR_DOCNAME[];

extern TCHAR STR_HOMEPAGE[];

//akelpad.cpp messages
extern TCHAR MSG_ERROR_LOADING_DLL[];
extern TCHAR MSG_ERROR_IN_MESSAGE_QUEUE[];
extern TCHAR MSG_ERROR_LIMIT_REACHED[];
extern TCHAR MSG_ERROR_NOT_ENOUGH_MEMORY_FOR_RICHEDIT[];
extern TCHAR MSG_ERROR_NOT_ENOUGH_MEMORY[];


//edit.cpp messages
extern TCHAR MSG_DOCUMENT_CHANGED[];
extern TCHAR MSG_FILE_WILL_BE_REOPENED[];
extern TCHAR MSG_WHETHER_APPEND_HEADER[];
extern TCHAR MSG_ERROR_IO[];
extern TCHAR MSG_ERROR_SETFONT[];
extern TCHAR MSG_ERROR_CANNOT_TRANSLATE[];
extern TCHAR MSG_ERROR_CANNOT_OPEN_FILE[];
extern TCHAR MSG_ERROR_SYNTAX[];
extern TCHAR MSG_TITLE_SAVING_IN_UNICODE[];
extern TCHAR MSG_WRONG_STRING[];
extern TCHAR MSG_ERROR_PRINT[];

//codepage.cpp messages
extern TCHAR MSG_WRONG_CODEPAGE[];
extern TCHAR MSG_CP_UNIMPLEMENTED[];

#endif
