//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by English.rc
//
#define MSG_ERROR_IN_MESSAGE_QUEUE               1
#define MSG_ERROR_LIMIT_REACHED                  2
#define MSG_ERROR_NOT_ENOUGH_MEMORY_FOR_EDIT     3
#define MSG_ERROR_NOT_ENOUGH_MEMORY              4
#define MSG_ERROR_BINARY                         5
#define MSG_ERROR_IO                             6
#define MSG_ERROR_SYNTAX                         8
#define MSG_ERROR_PRINT                          9
#define MSG_ERROR_RUN                            10
#define MSG_ERROR_LOAD_DLL                       12
#define MSG_ERROR_UNLOAD_DLL                     13
#define MSG_AUTOLOAD_IS_NOT_SUPPORTED            51
#define MSG_FUNCTION_NOT_FOUND                   52
#define MSG_UPDATE_PROGRAM                       53
#define MSG_PROGRAM_IS_NOT_SUPPORTED             54
#define MSG_UPDATE_PLUGIN                        55
#define MSG_PLUGIN_IS_NOT_SUPPORTED              56
#define MSG_UPDATE_LANGMODULE                    57
#define MSG_HOTKEY_EXISTS                        58
#define MSG_CANNOT_OPEN_FILE                     59
#define MSG_WRONG_STRING                         61
#define MSG_LONG_FILELIST                        62
#define MSG_DOCUMENT_CHANGED                     63
#define MSG_FILE_DOES_NOT_EXIST                  64
#define MSG_RECENTFILES_DELETED                  65
#define MSG_SEARCH_ENDED                         66
#define MSG_SEARCH_CYCLEPROMPT                   67
#define MSG_REPLACE_COUNT                        68
#define MSG_REPLACE_COUNT_ALLFILES               69
#define MSG_FILE_WILL_BE_REOPENED                70
#define MSG_FILE_CHANGED                         71
#define MSG_CP_UNIMPLEMENTED                     72
#define MSG_CP_MISMATCH                          73
#define MSG_ACCESSDENIED                         74
#define MSG_RESTART_PROGRAM                      75
#define MSG_SAVEIN_READONLY                      76
#define MSG_OVERWRITEPROMPT                      77
#define MSG_DOCUMENTSLIMIT                       78
#define STR_DOCNAME                              101
#define STR_MODIFIED                             102
#define STR_READONLY                             103
#define STR_COUNT                                104
#define STR_WITHOUT                              105
#define STR_AUTODETECT                           106
#define STR_RECENT_FILES_EMPTY                   107
#define STR_RECENT_FILES_DELETE_DEAD             108
#define STR_OPTIONS                              109
#define STR_LANGUAGE_NONE                        110
#define STR_FILE_FILTER                          111
#define STR_EXECUTABLE_FILTER                    112
#define STR_NONE                                 113
#define STR_PLUGIN                               114
#define STR_FUNCTION                             115
#define STR_HOTKEY                               116
#define STR_STATUS                               117
#define STR_RUNNING                              118
#define STR_FONT                                 119
#define STR_COLOR                                120
#define STR_HEADLINE                             121
#define STR_TOP                                  122
#define STR_BOTTOM                               123
#define STR_ELEMENT                              124
#define STR_STANDARDTHEME                        125
#define STR_TEXT                                 126
#define STR_BACKGROUND                           127
#define STR_SAMPLE                               128
#define STR_BASIC                                129
#define STR_SELECTION                            130
#define STR_ACTIVELINE                           131
#define STR_ACTIVELINEBORDER                     132
#define STR_ALTLINE                              133
#define STR_ALTLINEBORDER                        134
#define STR_ACTIVECOLUMN                         135
#define STR_COLUMNMARKER                         136
#define STR_CARET                                137
#define STR_URL                                  138
#define STR_ACTIVEURL                            139
#define STR_VISITURL                             140
#define STR_PAGEFIT                              141
#define STR_PAGEWIDTH                            142
#define STR_ALLFILES                             143
#define STR_ONLYMODIFIED                         144
#define STR_ONLYUNMODIFIED                       145
#define STR_INVERTSELECTION                      146
#define STR_NEWLINEDOT                           147
#define STR_MESSAGEBOX_OK                        148
#define STR_MESSAGEBOX_YES                       149
#define STR_MESSAGEBOX_NO                        150
#define STR_MESSAGEBOX_CANCEL                    151
#define STR_MESSAGEBOX_YESTOALL                  152
#define STR_MESSAGEBOX_NOTOALL                   153
#define STR_MESSAGEBOX_GOTO                      154
#define STR_MESSAGEBOX_TERMINATE                 155
#define STR_MESSAGEBOX_CONTINUE                  156
#define STR_AUTODETECT_RUSSIAN                   501
#define STR_AUTODETECT_EASTERNEUROPE             502
#define STR_AUTODETECT_WESTERNEUROPE             503
#define STR_AUTODETECT_TURKISH                   504
#define STR_AUTODETECT_CHINESE                   505
#define STR_AUTODETECT_JAPANESE                  506
#define STR_AUTODETECT_KOREAN                    507
#define RESERVED                                 1000
#define IDI_ICON_MAIN                            1001
#define IDI_ICON_EMPTY                           1002
#define IDC_CURSOR_DRAGMOVE                      1101
#define IDC_CURSOR_HANDOPEN                      1102
#define IDC_CURSOR_HANDCLOSE                     1103
#define IDA_ACCEL_GLOBAL                         1301
#define IDA_ACCEL_MAIN                           1302
#define IDD_OFN                                  2001
#define IDD_MDILIST                              2002
#define IDD_PRINTPREVIEW                         2003
#define IDD_FIND                                 2004
#define IDD_REPLACE                              2005
#define IDD_GOTO                                 2006
#define IDD_SAVEALLAS                            2007
#define IDD_RECODE                               2008
#define IDD_COLORS                               2009
#define IDD_PLUGINS                              2010
#define IDD_OPTIONS_GENERAL                      2011
#define IDD_OPTIONS_GENERAL_FILTER               2012
#define IDD_OPTIONS_REGISTRY                     2013
#define IDD_OPTIONS_EDITOR1                      2014
#define IDD_OPTIONS_EDITOR2                      2015
#define IDD_OPTIONS_ADVANCED                     2016
#define IDD_OPTIONS_ADVANCED1_3X                 2017
#define IDD_OPTIONS_ADVANCED2_3X                 2018
#define IDD_ABOUT                                2019
#define IDD_MESSAGEBOX                           2020
#define IDC_OFN_AUTODETECT                       2501
#define IDC_OFN_CODEPAGE                         2502
#define IDC_OFN_PREVIEW                          2503
#define IDC_OFN_CODEPAGE_LABEL                   2504
#define IDC_OFN_SHOWPLACESBAR                    2505
#define IDC_SAVEALLAS_CODEPAGE_CHECK             2531
#define IDC_SAVEALLAS_CODEPAGE_LIST              2532
#define IDC_SAVEALLAS_BOM                        2533
#define IDC_SAVEALLAS_NEWLINE_CHECK              2534
#define IDC_SAVEALLAS_NEWLINE_WIN                2535
#define IDC_SAVEALLAS_NEWLINE_UNIX               2536
#define IDC_SAVEALLAS_NEWLINE_MAC                2537
#define IDC_MDILIST_LIST                         2551
#define IDC_MDILIST_STATS                        2552
#define IDC_MDILIST_SEARCH                       2553
#define IDC_MDILIST_ARRANGE_GROUP                2554
#define IDC_MDILIST_HORZ                         2555
#define IDC_MDILIST_VERT                         2556
#define IDC_MDILIST_TABS_GROUP                   2557
#define IDC_MDILIST_UP                           2558
#define IDC_MDILIST_DOWN                         2559
#define IDC_MDILIST_SORT                         2560
#define IDC_MDILIST_FILES_GROUP                  2561
#define IDC_MDILIST_SAVE                         2562
#define IDC_MDILIST_CLOSE                        2563
#define IDC_MDILIST_ONLYNAMES                    2564
#define IDC_MDILIST_ALL                          2565
#define IDC_MDILIST_ONLYMODIFIED                 2566
#define IDC_MDILIST_ONLYUNMODIFIED               2567
#define IDC_MDILIST_INVERTSELECTION              2568
#define IDC_PREVIEW_BOX                          3001
#define IDC_PREVIEW_PRINT                        3002
#define IDC_PREVIEW_PAGESETUP                    3003
#define IDC_PREVIEW_FIRSTPAGE                    3004
#define IDC_PREVIEW_LASTPAGE                     3005
#define IDC_PREVIEW_PREVPAGE                     3006
#define IDC_PREVIEW_NEXTPAGE                     3007
#define IDC_PREVIEW_PAGECOUNT                    3008
#define IDC_PREVIEW_ZOOM                         3009
#define IDC_PREVIEW_ZOOMIN                       3010
#define IDC_PREVIEW_ZOOMOUT                      3011
#define IDC_PREVIEW_SELECTION                    3012
#define IDC_PREVIEW_CLOSE                        3013
#define IDC_SETREADONLY                          3051
#define IDC_SEARCH_FIND                          3052
#define IDC_SEARCH_REPLACE                       3053
#define IDC_SEARCH_MATCHCASE                     3054
#define IDC_SEARCH_WHOLEWORD                     3055
#define IDC_SEARCH_ESCAPESEQ                     3056
#define IDC_SEARCH_REGEXP                        3057
#define IDC_SEARCH_MULTILINE                     3058
#define IDC_SEARCH_BACKWARD                      3059
#define IDC_SEARCH_FORWARD                       3060
#define IDC_SEARCH_BEGINNING                     3061
#define IDC_SEARCH_INSEL                         3062
#define IDC_SEARCH_ALLFILES_GROUP                3063
#define IDC_SEARCH_ALLFILES                      3064
#define IDC_SEARCH_FIND_BUTTON                   3065
#define IDC_SEARCH_REPLACE_BUTTON                3066
#define IDC_SEARCH_ALL_BUTTON                    3067
#define IDC_SEARCH_REGEXP_ARROW                  3068
#define IDC_SEARCH_REGEXP_MENUDOT                3069
#define IDC_GOTO_NUMBER                          3101
#define IDC_GOTO_LINE                            3102
#define IDC_GOTO_OFFSET                          3103
#define IDC_RECODE_CODEPAGEFROM_LABEL            3151
#define IDC_RECODE_CODEPAGEFROM_LIST             3152
#define IDC_RECODE_CODEPAGETO_LABEL              3153
#define IDC_RECODE_CODEPAGETO_LIST               3154
#define IDC_RECODE_AUTODETECT                    3155
#define IDC_RECODE_PREVIEW                       3156
#define IDC_COLORS_LIST                          3201
#define IDC_COLORS_THEMENAME_LABEL               3202
#define IDC_COLORS_THEMENAME_COMBO               3203
#define IDC_COLORS_THEMESAVE                     3204
#define IDC_COLORS_THEMEDELETE                   3205
#define IDC_COLORS_BKIMAGEFILE_LABEL             3206
#define IDC_COLORS_BKIMAGEFILE_EDIT              3207
#define IDC_COLORS_BKIMAGEFILE_BROWSE            3208
#define IDC_COLORS_BKIMAGEALPHA_LABEL            3209
#define IDC_COLORS_BKIMAGEALPHA_EDIT             3210
#define IDC_COLORS_BKIMAGEALPHA_SPIN             3211
#define IDC_PLUGINS_LIST                         3251
#define IDC_PLUGINS_HOTKEY                       3252
#define IDC_PLUGINS_ASSIGN                       3253
#define IDC_PLUGINS_CALL                         3254
#define IDC_PLUGINS_HOTKEY_LABEL                 3255
#define IDC_PLUGINS_LIST_INFO                    3256
#define IDC_OPTIONS_EXECCOM                      3501
#define IDC_OPTIONS_EXECCOM_BROWSE               3502
#define IDC_OPTIONS_EXECDIR                      3503
#define IDC_OPTIONS_EXECDIR_BROWSE               3504
#define IDC_OPTIONS_CODEPAGE_RECOGNITION         3505
#define IDC_OPTIONS_CODEPAGE_RECOGNITION_BUFFER  3506
#define IDC_OPTIONS_DEFAULT_CODEPAGE             3507
#define IDC_OPTIONS_CODEPAGE_FILTER              3508
#define IDC_OPTIONS_CODEPAGES_FILTER_CUSTOM      3509
#define IDC_OPTIONS_CODEPAGES_FILTER_SYSTEM      3510
#define IDC_OPTIONS_CODEPAGES_FILTER_UP          3511
#define IDC_OPTIONS_CODEPAGES_FILTER_DOWN        3512
#define IDC_OPTIONS_CODEPAGES_FILTER_ADD         3513
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETE      3514
#define IDC_OPTIONS_CODEPAGES_FILTER_ADDALL      3515
#define IDC_OPTIONS_CODEPAGES_FILTER_DELETEALL   3516
#define IDC_OPTIONS_NEWFILE_CODEPAGE             3517
#define IDC_OPTIONS_NEWFILE_BOM                  3518
#define IDC_OPTIONS_NEWFILE_NEWLINE              3519
#define IDC_OPTIONS_SAVESETTINGS_REGISTRY        3551
#define IDC_OPTIONS_SAVESETTINGS_INI             3552
#define IDC_OPTIONS_SAVEHISTORY_REGISTRY         3553
#define IDC_OPTIONS_SAVEHISTORY_INI              3554
#define IDC_OPTIONS_SAVEPOSITIONS                3555
#define IDC_OPTIONS_SAVECODEPAGES                3556
#define IDC_OPTIONS_RECENTFILES_AMOUNT           3557
#define IDC_OPTIONS_RECENTFILES_AMOUNT_SPIN      3558
#define IDC_OPTIONS_RECENTFILES_CLEAR            3559
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT         3560
#define IDC_OPTIONS_SEARCHSTRINGS_AMOUNT_SPIN    3561
#define IDC_OPTIONS_SEARCHSTRINGS_CLEAR          3562
#define IDC_OPTIONS_FILETYPES_OPEN               3563
#define IDC_OPTIONS_ASSOCIATE_OPEN               3564
#define IDC_OPTIONS_FILETYPES_EDIT               3565
#define IDC_OPTIONS_ASSOCIATE_EDIT               3566
#define IDC_OPTIONS_FILETYPES_PRINT              3567
#define IDC_OPTIONS_ASSOCIATE_PRINT              3568
#define IDC_OPTIONS_TABSIZE                      3601
#define IDC_OPTIONS_TABSIZE_SPIN                 3602
#define IDC_OPTIONS_TABSIZE_SPACES               3603
#define IDC_OPTIONS_UNDO_LIMIT                   3604
#define IDC_OPTIONS_UNDO_LIMIT_SPIN              3605
#define IDC_OPTIONS_UNDO_DETAILED                3606
#define IDC_OPTIONS_WRAP_BY_WORDS                3607
#define IDC_OPTIONS_WRAP_BY_SYMBOLS              3608
#define IDC_OPTIONS_WRAP_LIMIT                   3609
#define IDC_OPTIONS_WRAP_LIMIT_SPIN              3610
#define IDC_OPTIONS_MARKER                       3611
#define IDC_OPTIONS_MARKER_SPIN                  3612
#define IDC_OPTIONS_CARETWIDTH                   3613
#define IDC_OPTIONS_CARETWIDTH_SPIN              3614
#define IDC_OPTIONS_CARETOUTEDGE                 3615
#define IDC_OPTIONS_CARETVERTLINE                3616
#define IDC_OPTIONS_CARETACTIVELINE              3617
#define IDC_OPTIONS_CARETACTIVELINEBORDER        3618
#define IDC_OPTIONS_ALTLINESKIP                  3619
#define IDC_OPTIONS_ALTLINESKIP_SPIN             3620
#define IDC_OPTIONS_ALTLINEFILL                  3621
#define IDC_OPTIONS_ALTLINEFILL_SPIN             3622
#define IDC_OPTIONS_ALTLINEBORDER                3623
#define IDC_OPTIONS_EDITMARGIN_LEFT              3624
#define IDC_OPTIONS_EDITMARGIN_LEFT_SPIN         3625
#define IDC_OPTIONS_EDITMARGIN_RIGHT             3626
#define IDC_OPTIONS_EDITMARGIN_RIGHT_SPIN        3627
#define IDC_OPTIONS_EDITMARGIN_TOP               3628
#define IDC_OPTIONS_EDITMARGIN_TOP_SPIN          3629
#define IDC_OPTIONS_EDITMARGIN_BOTTOM            3630
#define IDC_OPTIONS_EDITMARGIN_BOTTOM_SPIN       3631
#define IDC_OPTIONS_LINEGAP                      3632
#define IDC_OPTIONS_LINEGAP_SPIN                 3633
#define IDC_OPTIONS_MOUSELEFTMARGIN              3634
#define IDC_OPTIONS_MOUSERICHEDIT                3635
#define IDC_OPTIONS_MOUSEDRAGGING                3636
#define IDC_OPTIONS_RCLICKMOVECARET              3637
#define IDC_OPTIONS_URL_SHOW                     3638
#define IDC_OPTIONS_URL_SINGLECLICK              3639
#define IDC_OPTIONS_URL_DOUBLECLICK              3640
#define IDC_OPTIONS_URL_PREFIXES_ENABLE          3641
#define IDC_OPTIONS_URL_PREFIXES                 3642
#define IDC_OPTIONS_URL_DELIMITERS_ENABLE        3643
#define IDC_OPTIONS_URL_LEFTDELIMITERS           3644
#define IDC_OPTIONS_URL_RIGHTDELIMITERS          3645
#define IDC_OPTIONS_WORD_DELIMITERS_ENABLE       3646
#define IDC_OPTIONS_WORD_DELIMITERS              3647
#define IDC_OPTIONS_WORD_DELIMITERS_RESET        3648
#define IDC_OPTIONS_WRAP_DELIMITERS_ENABLE       3649
#define IDC_OPTIONS_WRAP_DELIMITERS              3650
#define IDC_OPTIONS_WRAP_DELIMITERS_RESET        3651
#define IDC_OPTIONS_SWITCH_KEYBLAYOUT            3701
#define IDC_OPTIONS_REMEMBER_KEYBLAYOUT          3702
#define IDC_OPTIONS_SILENTCLOSEEMPTY             3703
#define IDC_OPTIONS_LOGDATE                      3704
#define IDC_OPTIONS_SAVEIN_READONLY_MSG          3705
#define IDC_OPTIONS_DEFAULT_SAVE_EXT             3706
#define IDC_OPTIONS_REPLACEALL_CLOSE             3707
#define IDC_OPTIONS_REPLACEALL_NOMSG             3708
#define IDC_OPTIONS_INSELIFSEL                   3709
#define IDC_OPTIONS_CYCLESEARCH                  3710
#define IDC_OPTIONS_CYCLESEARCHPROMPT            3711
#define IDC_OPTIONS_MODELESSSAVEPOS              3712
#define IDC_ABOUT_ICON                           3901
#define IDC_ABOUT_VERSION                        3902
#define IDC_ABOUT_HOMEPAGE                       3903
#define IDC_ABOUT_EMAIL_KUZNETSOV                3904
#define IDC_ABOUT_EMAIL_SHENGALTS                3905
#define IDC_MESSAGEBOX_ICON                      3921
#define IDC_MESSAGEBOX_TEXT                      3922
#define IDC_MESSAGEBOX_YESTOALL                  3923
#define IDC_MESSAGEBOX_NOTOALL                   3924
#define IDC_MESSAGEBOX_GOTO                      3925
#define IDC_MESSAGEBOX_OK                        3926
#define IDC_MESSAGEBOX_YES                       3927
#define IDC_MESSAGEBOX_NO                        3928
#define IDM_MENU_MAIN                            4001
#define IDM_MENU_POPUP                           4002
#define IDM_POPUP_HEADLINE_SYMBOL                4011
#define IDM_POPUP_HEADLINE_PAGE_NUMBER           4012
#define IDM_POPUP_HEADLINE_FILENAME              4013
#define IDM_POPUP_HEADLINE_FILEDIR               4014
#define IDM_POPUP_HEADLINE_ALIGN_CENTER          4015
#define IDM_POPUP_HEADLINE_ALIGN_LEFT            4016
#define IDM_POPUP_HEADLINE_ALIGN_RIGHT           4017
#define IDC_STATIC                               -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11001
#define _APS_NEXT_COMMAND_VALUE         12001
#define _APS_NEXT_CONTROL_VALUE         13001
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
