//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LineBoard.rc
//
#define IDI_ICON_PLUGIN                 101
#define IDD_SETUP                       1001
#define IDC_PANEL_GROUP                 1101
#define IDC_SHOWBOARD                   1102
#define IDC_BACKGROUNDCOLOR_BUTTON      1103
#define IDC_BACKGROUNDCOLOR_LABEL       1104
#define IDC_TEXTCOLOR_BUTTON            1105
#define IDC_TEXTCOLOR_LABEL             1106
#define IDC_BORDERCOLOR_BUTTON          1107
#define IDC_BORDERCOLOR_LABEL           1108
#define IDC_BOOKMARKTEXTCOLOR_BUTTON    1109
#define IDC_BOOKMARKTEXTCOLOR_LABEL     1110
#define IDC_BOOKMARKBACKGROUNDCOLOR_BUTTON 1111
#define IDC_BOOKMARKBACKGROUNDCOLOR_LABEL 1112
#define IDC_BOOKMARKBORDERCOLOR_BUTTON  1113
#define IDC_BOOKMARKBORDERCOLOR_LABEL   1114
#define IDC_LINEUNSAVEDCOLOR_CHECK      1115
#define IDC_LINEUNSAVEDCOLOR_BUTTON     1116
#define IDC_LINEUNSAVEDCOLOR_LABEL      1117
#define IDC_LINESAVEDCOLOR_CHECK        1118
#define IDC_LINESAVEDCOLOR_BUTTON       1119
#define IDC_LINESAVEDCOLOR_LABEL        1120
#define IDC_LINEMODIFICATIONWIDTH_LABEL 1121
#define IDC_LINEMODIFICATIONWIDTH_EDIT  1122
#define IDC_LINEMODIFICATIONWIDTH_SPIN  1123
#define IDC_ROWTEXTCOLOR_BUTTON         1124
#define IDC_ROWTEXTCOLOR_LABEL          1125
#define IDC_RULERSCALECOLOR_BUTTON      1126
#define IDC_RULERSCALECOLOR_LABEL       1127
#define IDC_RULERCARETCOLOR_BUTTON      1128
#define IDC_RULERCARETCOLOR_LABEL       1129
#define IDC_RULERENABLE                 1130
#define IDC_RULERHEIGHT_EDIT            1131
#define IDC_RULERHEIGHT_SPIN            1132
#define IDC_RULERCARETWIDTH_LABEL       1133
#define IDC_RULERCARETWIDTH_EDIT        1134
#define IDC_RULERCARETWIDTH_SPIN        1135
#define IDC_BOOKMARK_GROUP              1136
#define IDC_SETBOOKMARK_LABEL           1137
#define IDC_SETBOOKMARK                 1138
#define IDC_DELBOOKMARK_LABEL           1139
#define IDC_DELBOOKMARK                 1140
#define IDC_DELALLBOOKMARK_LABEL        1141
#define IDC_DELALLBOOKMARK              1142
#define IDC_NEXTBOOKMARK_LABEL          1143
#define IDC_NEXTBOOKMARK                1144
#define IDC_PREVBOOKMARK_LABEL          1145
#define IDC_PREVBOOKMARK                1146
#define IDC_BOOKMARKLIST_LABEL          1147
#define IDC_BOOKMARKLIST                1148
#define IDC_REMEMBERBOOKMARKS           1149
#define IDC_BOOKMARKCHARHEIGHT          1150
#define IDC_CODERTHEME                  1151
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11001
#define _APS_NEXT_COMMAND_VALUE         12001
#define _APS_NEXT_CONTROL_VALUE         13001
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
